stages:
  - helm-publish

helm-publish:
  stage: helm-publish
  image:
    name: alpine/helm:latest
    entrypoint: [ "" ]
  script:
    - helm repo add --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD konga ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm package . --version $VERSION
    - helm cm-push konga-$VERSION.tgz konga
  rules:
    - if: $CI_COMMIT_TAG != null
      variables:
        VERSION: $CI_COMMIT_TAG
      when: always
