# Default values for konga.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pantsel/konga
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80


# Konga default configuration
config:
#   port: 1337
  node_env: production
#   ssl_key_path:
#   ssl_crt_path:
#   konga_hook_timeout: 60000
  db_adapter: mysql
#   db_uri:
  db_host: 1.2.3.4
  db_port: 3306
#   db_user:
#   db_password:
  db_database: konga
#   db_pg_schema: public
  log_level: warn
#   token_secret:
#   konga_node_data:
#   konga_user_data:

secrets:
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: konga-db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: konga-db-credentials
        key: password

# LDAP configuration for Konga
ldap: {}
# ldap:
#   auth_provider:
#   host:
#   bind_dn:
#   bind_pass:
#   user_search_base:
#   user_search_filter:
#   user_attrs:
#   group_search_base:
#   group_search_filter:
#   group_attrs:
#   group_reg:
#   attr_username:
#   attr_firstname:
#   attr_lastname:
#   attr_email:

# Ingress Configuration for Konga
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
